# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _brain
else:
    import _brain

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def new_uint32_tArray(nelements):
    return _brain.new_uint32_tArray(nelements)

def delete_uint32_tArray(ary):
    return _brain.delete_uint32_tArray(ary)

def uint32_tArray_getitem(ary, index):
    return _brain.uint32_tArray_getitem(ary, index)

def uint32_tArray_setitem(ary, index, value):
    return _brain.uint32_tArray_setitem(ary, index, value)
MAX_PACKET_LENGTH = _brain.MAX_PACKET_LENGTH
EEG_POWER_BANDS = _brain.EEG_POWER_BANDS
class Brain(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _brain.Brain_swiginit(self, _brain.new_Brain())

    def update(self, latestByte):
        return _brain.Brain_update(self, latestByte)

    def readErrors(self):
        return _brain.Brain_readErrors(self)

    def readCSV(self):
        return _brain.Brain_readCSV(self)

    def readSignalQuality(self):
        return _brain.Brain_readSignalQuality(self)

    def readAttention(self):
        return _brain.Brain_readAttention(self)

    def readMeditation(self):
        return _brain.Brain_readMeditation(self)

    def readPowerArray(self):
        return _brain.Brain_readPowerArray(self)

    def readDelta(self):
        return _brain.Brain_readDelta(self)

    def readTheta(self):
        return _brain.Brain_readTheta(self)

    def readLowAlpha(self):
        return _brain.Brain_readLowAlpha(self)

    def readHighAlpha(self):
        return _brain.Brain_readHighAlpha(self)

    def readLowBeta(self):
        return _brain.Brain_readLowBeta(self)

    def readHighBeta(self):
        return _brain.Brain_readHighBeta(self)

    def readLowGamma(self):
        return _brain.Brain_readLowGamma(self)

    def readMidGamma(self):
        return _brain.Brain_readMidGamma(self)
    __swig_destroy__ = _brain.delete_Brain

# Register Brain in _brain:
_brain.Brain_swigregister(Brain)

